version: '3.7'
services:
  trino-coordinator:
    image: 'trino-new:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
      - /E/docker/trino-getting-started-main/hive/trino-hdfs3/data:/home/trino/data:ro
      - /E/docker/trino-getting-started-main/hive/trino-hdfs3/plugin/llvm:/lib/trino/plugin/llvm:ro
      - /E/dockerVolume/hdfs:/home/dev/hdfs:ro
      - /E/docker/code:/home/dev/code:ro
      - /C/Users/luogo/Desktop/projects/ParserUtil:/home/dev/trino-gateway:ro
      - ./conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
      - ./conf/hdfs-site.xml:/etc/hadoop/conf/hdfs-site.xml:ro
    networks:
      - trino-network

  hadoop-node:
    image: 'ghcr.io/trinodb/testing/hive3.1-hive:latest'
    hostname: hadoop-node
    expose:
      - "9083"
      - "9864"
      - "9870"
      - "9000"
      - "10000"
    ports:
      - '3306:3306' # Metastore MySQL Database
      - '9083:9083' # Metastore Thrift
      - '9864:9864' # DataNode Web UI since Hadoop 3
      - '9870:9870' # NameNode Web UI since Hadoop 3
      - '9000:9000'
      - '8082:8082'
      - '10000:10000' # HiveServer2
    volumes:
      - ./conf/core-site.xml:/etc/hadoop/conf/core-site.xml:ro
      - ./data:/user/hive/:ro
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge
